version: '3.0'

services:

  locadoraapp:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile.dotnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    restart: always
    ports:
      - "80:80"

  database:
    image: mysql:5.6
    hostname: 'database'
    environment:
      MYSQL_DATABASE: Locadora
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - dbdata:/var/lib/mysql
    restart: always

  react:
    image: node:12
    build:
      context: .
      dockerfile: Dockerfile.react
    depends_on:
      - locadoraapp
    ports:
      - '3000:3000'
    environment:
      - APP=locadoraapp
volumes:
  dbdata:
